language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer self-update
  - composer install -n --prefer-dist
  -  cd tests/ && ../vendor/codeception/codeception/codecept build

script:
  - cd tests/ && ../vendor/codeception/codeception/codecept run